version: '3.4'

services:
  php-cli:
    image: digitalspacestudio/php-akeneo-pim:7.4
    build: './docker/php'
    command: sh -c 'while true; do sleep 1; done;'
    volumes:
      - './www:/var/www'
      - 'pim-var-cache:/var/www/var/cache'
      - 'pim-public-cache:/var/www/var/public/cache'
    networks:
      - 'pim'

  fpm:
    image: digitalspacestudio/php-akeneo-pim:7.4
    build: './docker/php'
    environment:
      COMPOSER_HOME: '/var/www/.composer'
    volumes:
      - './www:/var/www'
      - './docker/php/php-fpm.ini:/home/linuxbrew/.linuxbrew/etc/php/7.4/php-fpm.conf:ro'
      - './docker/php/php.ini:/home/linuxbrew/.linuxbrew/etc/php/7.4/php.ini:ro'
      - './docker/php/prepend.php:/home/linuxbrew/.linuxbrew/etc/php/7.4/prepend.php:ro'
      - './docker/php/entrypoint.sh:/entrypoint.sh:ro'
      - './docker/php/ecosystem.config.js:/ecosystem.config.js:ro'
      - './docker/php/msmtprc:/home/linuxbrew/.msmtprc:ro'
      - 'pim-var-cache:/var/www/var/cache'
      - 'pim-public-cache:/var/www/var/public/cache'
    working_dir: '/var/www'
    command: '/bin/bash /entrypoint.sh'
    networks:
      - 'pim'
    depends_on:
      - 'database'
      - "mongodb"
      - "mail"
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    networks:
      - 'pim'
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"

  xhgui:
    image: "xhgui/xhgui:0.18.1"
    volumes:
      - ./docker/xhgui/config:/var/www/xhgui/config
      - ./docker/xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${DOCKER_PORT_XHGUI:-8142}:80"
    depends_on:
      - 'mongodb'
    networks:
      - 'pim'
    healthcheck:
      test: nc -vz -w 1 localhost 80

  mail:
    image: "mailhog/mailhog"
    ports:
      - "${DOCKER_PORT_MAIL_HTTP:-8125}:8025"
    networks:
      - 'pim'
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 5s

  mongodb:
    image: percona/percona-server-mongodb:4.4
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DOCKER_PORT_MONGODB:-27017}:27017"
    networks:
      - 'pim'
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui

  database:
    image: 'mariadb:10.3.28'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'akeneo'
      MYSQL_DATABASE: 'akeneo'
      MYSQL_PASSWORD: 'akeneo'
    volumes:
      - './docker/mysql/mysql.initdb.d:/docker-entrypoint-initdb.d:ro'
      - './docker/mysql/my.cnf:/etc/mysql/conf.d/pim.cnf:ro'
    ports:
      - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'pim'
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx1024m}'
      discovery.type: 'single-node'
    ports:
      - '${DOCKER_PORT_ELASTICSEARCH:-9210}:9200'
    networks:
      - 'pim'

  nginx:
    image: 'crunchgeek/nginx-pagespeed'
    environment:
      NGINX_GEOIP: 'off'
      NGINX_PAGESPEED: 'on'
      NGINX_PAGESPEED_IMG: 'on'
      NGINX_PAGESPEED_JS: 'on'
      NGINX_PAGESPEED_CSS: 'on'
      NGINX_PAGESPEED_STORAGE: 'files'
    depends_on:
      - 'fpm'
      - 'database'
    ports:
      - '${DOCKER_PORT_HTTP:-8182}:80'
    volumes:
      - './www:/var/www:ro'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './docker/nginx/pagespeed.conf:/etc/nginx/pagespeed.conf:ro'
      - 'pim-public-cache:/var/www/var/public/cache:ro'
    networks:
      - 'pim'
    healthcheck:
      test: '[ $$(curl -o /dev/null -s -w "%\{http_code\}" -L http://localhost/) -eq 200 ]]'
      timeout: 10s
      start_period: 10s

networks:
  pim:

volumes:
  pim-var-cache:
    driver: local
  pim-public-cache:
    driver: local